version: "2"

services:
  consul-node1:
    image: progrium/consul
    container_name: consul-node1
    command: -server -bootstrap-expect 3
    networks:
      - consul
    ports:
      - 8400:8400
      - 8500:8500
      - 8600:53/udp

  consul-node2:
    image: progrium/consul
    container_name: consul-node2
    command: -server -join consul-node1
    depends_on:
      - consul-node1
    networks:
      - consul

  consul-node3:
    image: progrium/consul
    container_name: consul-node3
    command: -server -join consul-node1
    depends_on:
      - consul-node1
    networks:
      - consul

networks:
  consul:
    driver: bridge
